### ISSUE TITLE
Is it possible (or better) to change api client to middleware structure

### ISSUE THREAD

**Issue by WJWang** [Monte9/react-native-starter#1]
Would it better to wrap current [APIClient](https://github.com/Monte9/react-native-starter/blob/master/app/api/APIClient.js) with a [redux middleware](http://redux.js.org/docs/advanced/Middleware.html)?

I have do some similar things in my [web template](https://github.com/WJWang/web-template/blob/master/client/middlewares/apiMiddleware.js), and I not sure can it apply in react native.

**Comment by Monte9** [comment]
Good question, @WJWang! I am not sure what the best practices for the API client in React Native are. Any good reference that you have come across for React that you can link me to?

**Comment by WJWang** [comment]
There is an example provided by redux project [real-world](https://github.com/reactjs/redux/blob/master/examples/real-world/src/middleware/api.js)
